theme: jekyll-theme-minimal # Your Jekyll theme
title: ARJUN <br> VADEHRA
description: Spacecraft Engineer

# Include custom assets
include:
  - style.css

# Specify custom styles
sass:
  style: compressed
